# Generated by Django 4.0.4 on 2022-06-01 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='dsa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
